spring.application.name=stage-talan
# ====== DATABASE (PostgreSQL) ======
spring.datasource.url=jdbc:postgresql://localhost:5432/talan
spring.datasource.username=postgres
spring.datasource.password=postgres

# ====== JPA / Hibernate ======
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ====== SERVER CONFIG ======
# (Change le port si 8080 est déjà utilisé)
server.port=8080

# ====== JWT CONFIGURATION ======
jwt.secret=ee57b34a99614ae59334e62d6b1f6f
jwt.expiration=3600000  

# ====== LOGGING (optionnel) ======
logging.level.org.springframework.security=DEBUG

# ====== Mail config ======
spring.mail.username=eventtalan@gmail.com
spring.mail.password=mvtt ludb vfcm wmfd
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

